name: Slack message

on:
  check_suite:
    types: ['completed']

jobs:
  message:
    name: After CI failure
    # if: github.event.check_suite.conclusion != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Obtain failed CI run
        uses: octokit/request-action@v2.x
        id: get_failed_check_run
        with:
          route: GET /repos/${{ github.repository }}/check-suites/${{ github.event.check_suite.id }}/check-runs?status=completed
          mediaType: '{"previews": ["antiope"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post message on Slack
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" -H "Content-type: application/json" --data ${{ env.DATA }} https://slack.com/api/chat.postMessage
        env:
          DATA: '{
                    "channel": "${{ secrets.SLACK_CHANNEL }}",
                    "text": "Hello world"
                 }'